services:

  gitlab:
    image: 'gitlab/gitlab-ce:18.10.3-ce.0'
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.example.com.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.example.com.key'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['initial_root_password'] = 'strongpassword'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './.data/gitlab/config:/etc/gitlab'
      - './.data/gitlab/config/ssl:/etc/gitlab/ssl'
      - './.data/gitlab/data:/var/opt/gitlab'
      - './.data/gitlab/logs:/var/log/gitlab'
    shm_size: '256m'
    networks:
      gitlab-worker:

  dind:
    image: docker:dind
    hostname: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_SAN=DNS:dind
    volumes:
      - dind-storage:/var/lib/docker
      - certs:/certs
      - dind-share-volume:/etc/dind-share-folder
    networks:
      gitlab-worker:
    extra_hosts:
      - "gitlab.example.com:192.168.1.100"

  runner:
    image: gitlab/gitlab-runner
    depends_on:
      - dind
      - gitlab
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - certs:/certs:ro
      - runner-config:/etc/gitlab-runner
      - ./.data/gitlab/config/ssl/gitlab.example.com.crt:/etc/gitlab-runner/certs/gitlab.example.com.crt:ro
    networks:
      gitlab-worker:
    extra_hosts:
      - "gitlab.example.com:192.168.1.100"

  register-runner-docker:
    image: gitlab/gitlab-runner
    depends_on:
      - dind
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        if [ ! -f /etc/gitlab-runner/config.toml ]; then
          echo "Config does not exist, registering runner..."
          gitlab-runner register \
            --non-interactive \
            --locked=false \
            --name="GitLab Docker Runner" \
            --executor=docker \
            --docker-image=ubuntu:latest \
            --docker-host=tcp://dind:2376 \
            --docker-volumes="/etc/dind-share-folder:/etc/dind-share-folder" \
            --docker-extra-hosts="gitlab.example.com:192.168.1.100" \
            --tag-list="docker,ubuntu" \
            --run-untagged=true \
            --tls-ca-file=/etc/gitlab-runner/certs/gitlab.example.com.crt
        else
          echo "Runner config already exists, skipping registration"
        fi
    environment:
      - CI_SERVER_URL=https://gitlab.example.com
      - REGISTRATION_TOKEN=HwNAw6xfxkG71gBsQUtp
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - certs:/certs:ro
      - runner-config:/etc/gitlab-runner
      - ./.data/gitlab/config/ssl/gitlab.example.com.crt:/etc/gitlab-runner/certs/gitlab.example.com.crt:ro
    profiles:
      - manual
    networks:
      gitlab-worker:
    extra_hosts:
      - "gitlab.example.com:192.168.1.100"

  cli:
    image: docker:cli
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - certs:/certs:ro
    depends_on:
      - dind
    profiles:
      - manual
    networks:
      gitlab-worker:
    extra_hosts:
      - "gitlab.example.com:host-gateway"

  busybox:
    image: busybox
    profiles:
      - manual
    networks:
      gitlab-worker:
    extra_hosts:
      - "gitlab.example.com:host-gateway"

volumes:
  runner-config:
  dind-storage:
  certs:
  dind-share-volume:


networks:
  gitlab-worker:
