services:
  gitlab:
    image: gitlab/gitlab-ce:18.10.3-ce.0
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        letsencrypt['enable'] = false
        external_url 'http://gitlab.example.com'
        gitlab_rails['initial_root_password'] = 'your_password'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
    restart: no
    networks:
      - gitlab-network

  dind:
    image: docker:24.0.5-dind
    container_name: dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_TLS_SAN: "DNS:dind"
    volumes:
      - dind-storage:/var/lib/docker
      - certs:/certs
    healthcheck:
      test: [ "CMD", "docker", "info" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - gitlab-runner_data:/etc/gitlab-runner
      - certs:/certs:ro
    networks:
      - gitlab-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab-runner_data:
  dind-storage:
  certs:

networks:
  gitlab-network: