apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: curl-loop
          image: curlimages/curl:latest
          command: ['/bin/sh']
          args:
            - "-c"
            - |
              while true; do
                echo "======= call curl ========"
                curl -s backend-service:80
                echo
                sleep 5
              done
