apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
  labels:
    app: multi-container-app
spec:
  containers:
    #main app
    - name: main-app
      image: dbclinton/simple-app:latest
      ports:
        - containerPort: 5000
      env:
        - name: MESSAGE
          value: "Hello from the main app container"
    #logging sidecar
    - name: logger-app
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo 'hi, i am a sidecar'; sleep 5; done"]
