services:

  create-certificate:
    image: alpine/openssl:3.5.6
    restart: no
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        if [ ! -f /app/ssl/gitlab.example.com.key ] || [ ! -f /app/ssl/gitlab.example.com.crt ]; then
          echo "Generating self-signed certificate with SAN..."
          openssl req -x509 -newkey rsa:4096 -sha256 -days 10 -nodes \
            -keyout /app/ssl/gitlab.example.com.key \
            -out    /app/ssl/gitlab.example.com.crt \
            -subj "/O=HOME/CN=gitlab.example.com" \
            -addext "subjectAltName=DNS:gitlab.example.com,IP:127.0.0.1"
        else
          echo "Self-signed certificate exists, skipping"
          ls /app/ssl -a
        fi
    volumes:
      - './.secrets/create-certificate_SERVICE/ssl:/app/ssl'

  gitlab:
    image: gitlab/gitlab-ce:18.10.4-ce.0
    container_name: gitlab
    restart: always
    depends_on:
      create-certificate:
        condition: service_completed_successfully
    hostname: 'gitlab.example.com'
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.example.com.key"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['initial_root_password'] = 'strongpassword'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './.secrets/create-certificate_SERVICE/ssl:/etc/gitlab/ssl:ro'
      - './.data/gitlab_SERVICE/config:/etc/gitlab'
      - './.data/gitlab_SERVICE/logs:/var/log/gitlab'
      - './.data/gitlab_SERVICE/data:/var/opt/gitlab'
    networks:
      - gitlab-internal

  dind:
    image: docker:29.4.1-dind
    hostname: dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_SAN=DNS:dind
    volumes:
      - ./.secrets/dind_SERVICE/certs:/certs
      - './.data/dind_SERVICE/dind-storage:/var/lib/docker'
    networks:
      - gitlab-worker

  cli:
    #  docker compose run cli docker ps
    image: docker:29.4.1-cli
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - ./.secrets/dind_SERVICE/certs:/certs:ro
    depends_on:
      - dind
    restart: no
    profiles:
      - manual
    networks:
      - gitlab-worker

  ubuntu:
    # docker compose run ubuntu
    #  git clone https://gitlab.example.com/root/abc.git
    image: ubuntu:22.04
    volumes:
      - ./.secrets/create-certificate_SERVICE/ssl:/gitlab/certs:ro
    depends_on:
      create-certificate:
        condition: service_completed_successfully
    profiles:
      - manual
    networks:
      - gitlab-worker
    extra_hosts:
      - "gitlab.example.com:host-gateway"
    command: ["/bin/bash","-c", "\
      echo '****************** Installing missing packages (long/can break)...' && \
      apt update -qq --fix-missing && apt install -yqq ca-certificates git curl wget iputils-ping && \
      echo '****************** PING gitlab...' && \
      ping -c 1 gitlab.example.com && \
      echo '****************** Validate untrusted certificate...' && \
      echo | openssl s_client -connect gitlab.example.com:443 2>&1 | grep 'Verify return code' && \
      echo '****************** Installing certificate...' && \
      cp /gitlab/certs/gitlab.example.com.crt /usr/local/share/ca-certificates/ && \
      update-ca-certificates && \
      echo '****************** Validate installed certificate...' && \
      echo | openssl s_client -connect gitlab.example.com:443 2>&1 | grep 'Verify return code' && \
      echo '****************** DONE...' && \
      /bin/bash
    "]
    tty: true
    stdin_open: true


networks:
  gitlab-internal:
  gitlab-worker:
