services:

  create-certificate:
    image: alpine/openssl:3.5.6
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        if [ ! -f /app/ssl/gitlab.example.com.key ] || [ ! -f /app/ssl/gitlab.example.com.crt ]; then
          echo "Generating self-signed certificate with SAN..."
          openssl req -x509 -newkey rsa:4096 -sha256 -days 10 -nodes \
            -keyout /app/ssl/gitlab.example.com.key \
            -out    /app/ssl/gitlab.example.com.crt \
            -subj "/O=HOME/CN=gitlab.example.com" \
            -addext "subjectAltName=DNS:gitlab.example.com,IP:127.0.0.1"
        else
          echo "Self-signed certificate exists, skipping"
          ls /app/ssl -a
        fi
    volumes:
      - './.secrets/create-certificate_SERVICE/ssl:/app/ssl'

  gitlab:
    image: gitlab/gitlab-ce:18.10.4-ce.0
    container_name: gitlab
    restart: always
    depends_on:
      create-certificate:
        condition: service_completed_successfully
    hostname: 'gitlab.example.com'
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.example.com.key"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['initial_root_password'] = 'strongpassword'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './.secrets/create-certificate_SERVICE/ssl:/etc/gitlab/ssl:ro'
      - './.data/gitlab_SERVICE/config:/etc/gitlab'
      - './.data/gitlab_SERVICE/logs:/var/log/gitlab'
      - './.data/gitlab_SERVICE/data:/var/opt/gitlab'
    networks:
      - gitlab-internal

  dind:
    image: docker:29.4.1-dind
    hostname: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_SAN=DNS:dind
    volumes:
      - ./.secrets/dind_SERVICE/certs:/certs
      - './.data/dind_SERVICE/dind-storage:/var/lib/docker'
    networks:
      gitlab-worker:

  cli:
    image: docker:29.4.1-cli
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - ./.secrets/dind_SERVICE/certs:/certs:ro
    depends_on:
      - dind
    profiles:
      - manual
    networks:
      gitlab-worker:
  #  docker compose run cli docker ps

networks:
  gitlab-internal:
  gitlab-worker:
