services:
  gitlab:
    image: gitlab/gitlab-ce:18.10.4-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        letsencrypt['enable'] = true
        nginx['redirect_http_to_https'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = 'supersecret'
    ports:
      - '80:80'
      - '443:443'
      - '2222:2222'
    volumes:
      - './.data/GITLAB_HOME/config:/etc/gitlab'
      - './.data/GITLAB_HOME/logs:/var/log/gitlab'
      - './.data/GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab-internal

networks:
  gitlab-internal:
